services:
  auto-streamer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auto-streamer
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
      - ./config.json:/app/config.json
    environment:
      - OUTPUT_DIR=/data/output
      - TZ=America/Sao_Paulo
      - RTMP_URL
      - STREAM_KEY
      - OPENAI_API_KEY
      - ADMIN_PASS_HASH
    restart: unless-stopped
